# Prepare decision-rationale sentences

## Slob.c

In [ ]:
import pandas as pd
df_slob_commits = pd.read_csv('generalization_results_on_the_slob.csv' , sep=';', encoding ='latin-1')
df_slob_commits

commit ID  \
0    C_kwDOACN7MtoAKDY2MzBlOTUwZDUzMmZmYWJjZTNhNGJk...   
1    C_kwDOACN7MtoAKDY2MzBlOTUwZDUzMmZmYWJjZTNhNGJk...   
2    C_kwDOACN7MtoAKDY2MzBlOTUwZDUzMmZmYWJjZTNhNGJk...   
3    C_kwDOACN7MtoAKDA1YTk0MDY1NmUxZWIyMDI2ZDllZTMx...   
4    C_kwDOACN7MtoAKDA1YTk0MDY1NmUxZWIyMDI2ZDllZTMx...   
..                                                 ...   
828  MDY6Q29tbWl0MjMyNTI5ODoxMGNlZjYwMjk1MDI5MTViZG...   
829  MDY6Q29tbWl0MjMyNTI5ODoxMGNlZjYwMjk1MDI5MTViZG...   
830  MDY6Q29tbWl0MjMyNTI5ODoxMGNlZjYwMjk1MDI5MTViZG...   
831  MDY6Q29tbWl0MjMyNTI5ODoxMGNlZjYwMjk1MDI5MTViZG...   
832  MDY6Q29tbWl0MjMyNTI5ODoxMGNlZjYwMjk1MDI5MTViZG...   

                                                  text  predicted_decision  \
0                               mm/slob: remove slob.c                   1   
1                       Remove the SLOB implementation                   1   
2                     RIP SLOB allocator (2006 - 2023)                   0   
3               slab: Introduce kmalloc_size_roundup()                   1   
4    In the effort to help the compiler reason abou...                   1   
..                                                 ...                 ...   
828  It's been tested extensively in the Linux-tiny...                   0   
829   I've also\nstress-tested it with make -j 8 co...                   1   
830  Here's a comparison for otherwise identical bu...                   1   
831  $ size vmlinux*\n   text    data     bss     d...                   1   
832                    SLAB          SLOB      delt...                   1   

     predicted_rationale  
0                      1  
1                      1  
2                      0  
3                      0  
4                      1  
..                   ...  
828                    0  
829                    0  
830                    1  
831                    1  
832                    1  

[833 rows x 4 columns]

In [ ]:
df_slob_commits_decision_rationale_sentences = df_slob_commits[(df_slob_commits["predicted_decision"] == 1) & (df_slob_commits["predicted_rationale"] == 1 )]
df_slob_commits_decision_rationale_sentences

commit ID  \
0    C_kwDOACN7MtoAKDY2MzBlOTUwZDUzMmZmYWJjZTNhNGJk...   
1    C_kwDOACN7MtoAKDY2MzBlOTUwZDUzMmZmYWJjZTNhNGJk...   
4    C_kwDOACN7MtoAKDA1YTk0MDY1NmUxZWIyMDI2ZDllZTMx...   
6    C_kwDOACN7MtoAKDA1YTk0MDY1NmUxZWIyMDI2ZDllZTMx...   
12   C_kwDOACN7MtoAKDA1YTk0MDY1NmUxZWIyMDI2ZDllZTMx...   
..                                                 ...   
819  MDY6Q29tbWl0MjMyNTI5ODo5OTM0YTc5MzllMWNkY2U2Mm...   
820  MDY6Q29tbWl0MjMyNTI5ODo5OTM0YTc5MzllMWNkY2U2Mm...   
830  MDY6Q29tbWl0MjMyNTI5ODoxMGNlZjYwMjk1MDI5MTViZG...   
831  MDY6Q29tbWl0MjMyNTI5ODoxMGNlZjYwMjk1MDI5MTViZG...   
832  MDY6Q29tbWl0MjMyNTI5ODoxMGNlZjYwMjk1MDI5MTViZG...   

                                                  text  predicted_decision  \
0                               mm/slob: remove slob.c                   1   
1                       Remove the SLOB implementation                   1   
4    In the effort to help the compiler reason abou...                   1   
6    For most allocations, this works well,\nas the...                   1   
12   Instead of the caller choosing its own next be...                   1   
..                                                 ...                 ...   
819                        [PATCH] SLOB=y && SMP=y fix                   1   
820  fix CONFIG_SLOB=y (when CONFIG_SMP=y): get rid...                   1   
830  Here's a comparison for otherwise identical bu...                   1   
831  $ size vmlinux*\n   text    data     bss     d...                   1   
832                    SLAB          SLOB      delt...                   1   

     predicted_rationale  
0                      1  
1                      1  
4                      1  
6                      1  
12                     1  
..                   ...  
819                    1  
820                    1  
830                    1  
831                    1  
832                    1  

[252 rows x 4 columns]

##drivers/Button.c

In [ ]:
import pandas as pd
df_button_commits = pd.read_csv('generalization_results_on_the_button.csv' , sep=';', encoding ='latin-1')
df_button_commits

commit ID  \
0    C_kwDOACN7MtoAKDE2ZjcwZmVhYWJlOWZkZTBhZjcwM2Yy...   
1    C_kwDOACN7MtoAKDE2ZjcwZmVhYWJlOWZkZTBhZjcwM2Yy...   
2    C_kwDOACN7MtoAKDE2ZjcwZmVhYWJlOWZkZTBhZjcwM2Yy...   
3    C_kwDOACN7MtoAKDE2ZjcwZmVhYWJlOWZkZTBhZjcwM2Yy...   
4    C_kwDOACN7MtoAKGU0ZTYyZDVmZDhlY2IwZWE0MTc0YWZk...   
..                                                 ...   
571  MDY6Q29tbWl0MjMyNTI5ODoxZGExNzdlNGMzZjQxNTI0ZT...   
572  MDY6Q29tbWl0MjMyNTI5ODoxZGExNzdlNGMzZjQxNTI0ZT...   
573  MDY6Q29tbWl0MjMyNTI5ODoxZGExNzdlNGMzZjQxNTI0ZT...   
574  MDY6Q29tbWl0MjMyNTI5ODoxZGExNzdlNGMzZjQxNTI0ZT...   
575  MDY6Q29tbWl0MjMyNTI5ODoxZGExNzdlNGMzZjQxNTI0ZT...   

                                                  text  predicted_decision  \
0              ACPI: button: trigger wakeup key events                   1   
1    Andorid can wakeup from various wakeup sources...                   0   
2    Regarding pressing acpi power button, it can r...                   0   
3    So, send wakeup key event to user space during...                   1   
4    ACPI: button: Use different notify handlers fo...                   1   
..                                                 ...                 ...   
571                                   Linux-2.6.12-rc2                   1   
572                       Initial git repository build                   1   
573  I'm not bothering with the full history,\neven...                   1   
574  We can create a separate "historical" git\narc...                   1   
575                                        Let it rip!                   1   

     predicted_rationale  
0                      1  
1                      1  
2                      0  
3                      0  
4                      1  
..                   ...  
571                    1  
572                    1  
573                    0  
574                    1  
575                    0  

[576 rows x 4 columns]

In [ ]:
df_button_commits_decision_rationale_sentences = df_button_commits[(df_button_commits["predicted_decision"] == 1) & (df_button_commits["predicted_rationale"] == 1 )]
df_button_commits_decision_rationale_sentences

commit ID  \
0    C_kwDOACN7MtoAKDE2ZjcwZmVhYWJlOWZkZTBhZjcwM2Yy...   
4    C_kwDOACN7MtoAKGU0ZTYyZDVmZDhlY2IwZWE0MTc0YWZk...   
5    C_kwDOACN7MtoAKGU0ZTYyZDVmZDhlY2IwZWE0MTc0YWZk...   
7    C_kwDOACN7MtoAKDBkNTExNTdkZmFhYzA1ZWE2NjYxNmQ4...   
14   C_kwDOACN7MtoAKDZjMGViNWJhMzUwMGY2ZGEzNjczNTFm...   
..                                                 ...   
567  MDY6Q29tbWl0MjMyNTI5ODpiMzRhODAzMGVlYWI0ZDU5ZG...   
570  MDY6Q29tbWl0MjMyNTI5ODpiZDQ2OThkYWQzMDIzYWUxMz...   
571  MDY6Q29tbWl0MjMyNTI5ODoxZGExNzdlNGMzZjQxNTI0ZT...   
572  MDY6Q29tbWl0MjMyNTI5ODoxZGExNzdlNGMzZjQxNTI0ZT...   
574  MDY6Q29tbWl0MjMyNTI5ODoxZGExNzdlNGMzZjQxNTI0ZT...   

                                                  text  predicted_decision  \
0              ACPI: button: trigger wakeup key events                   1   
4    ACPI: button: Use different notify handlers fo...                   1   
5    Since the lid handling in acpi_button_notify()...                   1   
7    Rework the ACPI button driver to install notif...                   1   
14   1 device_remove()->\n2   bus->remove()->\n3   ...                   1   
..                                                 ...                 ...   
567     [ACPI] restore /proc/acpi/button/ (ala 2.6.12)                   1   
570                           delete /proc/acpi/button                   1   
571                                   Linux-2.6.12-rc2                   1   
572                       Initial git repository build                   1   
574  We can create a separate "historical" git\narc...                   1   

     predicted_rationale  
0                      1  
4                      1  
5                      1  
7                      1  
14                     1  
..                   ...  
567                    1  
570                    1  
571                    1  
572                    1  
574                    1  

[191 rows x 4 columns]

## OSS projects

In [ ]:
import pandas as pd
df_oss_commits = pd.read_csv('generalization_results_on_the_commit_messages_paper.csv' , sep=';', encoding ='latin-1')
df_oss_commits

repo_id  label                                                url  \
0           4      0  https://github.com/square/okhttp/commit/2fd0da...   
1           2      0  https://github.com/apache/dubbo/commit/9e9e778...   
2           3      0  https://github.com/square/retrofit/commit/0754...   
3           4      3  https://github.com/square/okhttp/commit/c310d2...   
4           2      0  https://github.com/apache/dubbo/commit/7f262f9...   
...       ...    ...                                                ...   
1592        2      0  https://github.com/apache/dubbo/commit/789775b...   
1593        2      2  https://github.com/apache/dubbo/commit/84d355f...   
1594        2      0  https://github.com/apache/dubbo/commit/3bdc316...   
1595        5      0  https://github.com/spring-projects/spring-boot...   
1596        2      2  https://github.com/apache/dubbo/commit/055f1cc...   

                                           new_message1  Decision  Rationale  \
0                  Update concurrency.md ( <pr_link> )          1          1   
1      Optimize_hessian_desr_performance ( <pr_link> )          1          1   
2                               Add <iden> annotation.          1          1   
3     workaround broken system  <file_name>  behaviour          1          0   
4            simplify map empty judgment ( <pr_link> )          1          1   
...                                                 ...       ...        ...   
1592  Change <iden> to regular list in  <file_name> ...         1          1   
1593                           code rule ( <pr_link> )          0          1   
1594          replace <iden> with <iden> ( <pr_link> )          1          1   
1595  Update  <file_name> <enter> Replace line break...         1          1   
1596  [Dubbo-4871] fix cache file name issue in wind...         0          1   

      predicted_decision  predicted_rationale  
0                      1                    1  
1                      1                    0  
2                      1                    1  
3                      1                    1  
4                      1                    1  
...                  ...                  ...  
1592                   1                    1  
1593                   1                    0  
1594                   1                    0  
1595                   1                    1  
1596                   1                    1  

[1597 rows x 8 columns]

In [ ]:
df_oss_commits.value_counts("repo_id")

repo_id
5    373
1    320
4    318
2    303
3    283
Name: count, dtype: int64

from URL field:

-repo_id = 1 ==> junit

-repo_id = 2 => apache/dubbo

-repo_id = 3 => square retrofit

-repo_id = 4 => square/ oktthp

-repo_id = 5 => spring_boot

In [ ]:
df_oss_commits_1 = df_oss_commits[df_oss_commits["repo_id"] == 1]
df_oss_commits_2 = df_oss_commits[df_oss_commits["repo_id"] == 2]
df_oss_commits_3 = df_oss_commits[df_oss_commits["repo_id"] == 3]
df_oss_commits_4 = df_oss_commits[df_oss_commits["repo_id"] == 4]
df_oss_commits_5 = df_oss_commits[df_oss_commits["repo_id"] == 5]

In [ ]:
df_oss_commits_4

repo_id  label                                                url  \
0           4      0  https://github.com/square/okhttp/commit/2fd0da...   
3           4      3  https://github.com/square/okhttp/commit/c310d2...   
14          4      2  https://github.com/square/okhttp/commit/e3cd9b...   
19          4      0  https://github.com/square/okhttp/commit/02b08f...   
22          4      0  https://github.com/square/okhttp/commit/f87d32...   
...       ...    ...                                                ...   
1557        4      0  https://github.com/square/okhttp/commit/652f3a...   
1558        4      0  https://github.com/square/okhttp/commit/474c23...   
1562        4      3  https://github.com/square/okhttp/commit/28434c...   
1566        4      2  https://github.com/square/okhttp/commit/eae6f3...   
1567        4      0  https://github.com/square/okhttp/commit/fce60e...   

                                           new_message1  Decision  Rationale  \
0                  Update concurrency.md ( <pr_link> )          1          1   
3     workaround broken system  <file_name>  behaviour          1          0   
14     Fixes <issue_link> - <iden> based <iden> setup.          0          1   
19    Allow HTAB in header values.  <enter> RFC 7230...         1          1   
22         README: <iden> changes for OkHttp <version>          1          1   
...                                                 ...       ...        ...   
1557                                  HTTP/1 >> <iden>          1          1   
1558  Properly parse <iden> 7235 authentication head...         1          1   
1562   Add wildcard hostnames support in  <file_name>           1          0   
1566  Fix correctness of WebSocketReader reserved fl...         0          1   
1567  Document sharing an instance with additional c...         1          1   

      predicted_decision  predicted_rationale  
0                      1                    1  
3                      1                    1  
14                     0                    1  
19                     0                    1  
22                     1                    1  
...                  ...                  ...  
1557                   0                    0  
1558                   0                    0  
1562                   1                    1  
1566                   1                    1  
1567                   0                    0  

[318 rows x 8 columns]

In [ ]:
df_oss_commits_1_decision_rationale_sentences = df_oss_commits_1[(df_oss_commits_1["predicted_decision"] == 1) & (df_oss_commits_1["predicted_rationale"] == 1 )]
df_oss_commits_2_decision_rationale_sentences = df_oss_commits_2[(df_oss_commits_2["predicted_decision"] == 1) & (df_oss_commits_2["predicted_rationale"] == 1 )]
df_oss_commits_3_decision_rationale_sentences = df_oss_commits_3[(df_oss_commits_3["predicted_decision"] == 1) & (df_oss_commits_3["predicted_rationale"] == 1 )]
df_oss_commits_4_decision_rationale_sentences = df_oss_commits_4[(df_oss_commits_4["predicted_decision"] == 1) & (df_oss_commits_4["predicted_rationale"] == 1 )]
df_oss_commits_5_decision_rationale_sentences = df_oss_commits_5[(df_oss_commits_5["predicted_decision"] == 1) & (df_oss_commits_5["predicted_rationale"] == 1 )]

In [ ]:
df_oss_commits_5_decision_rationale_sentences  # See how many sentences before running ChatGPT. Do not exceed 150 sentences!

repo_id  label                                                url  \
9           5      0  https://github.com/spring-projects/spring-boot...   
24          5      0  https://github.com/spring-projects/spring-boot...   
31          5      2  https://github.com/spring-projects/spring-boot...   
34          5      0  https://github.com/spring-projects/spring-boot...   
36          5      0  https://github.com/spring-projects/spring-boot...   
...       ...    ...                                                ...   
1569        5      0  https://github.com/spring-projects/spring-boot...   
1575        5      0  https://github.com/spring-projects/spring-boot...   
1577        5      0  https://github.com/spring-projects/spring-boot...   
1579        5      2  https://github.com/spring-projects/spring-boot...   
1595        5      0  https://github.com/spring-projects/spring-boot...   

                                           new_message1  Decision  Rationale  \
9     Fix typo `<iden>` -> `<iden>`  <enter> See  <p...         1          1   
24    Ensure checking customizer ordering  <enter> S...         1          1   
31    Fix conditions that lead to auto-configure <id...         0          1   
34    Fix documentation example  <enter> Previously,...         1          1   
36    Replace use of deprecated Reactor <iden> in te...         1          1   
...                                                 ...       ...        ...   
1569  Add  <file_name>  option for  <file_name>  bui...         1          1   
1575  Add XMLUnit to spring-boot-starter-test  <ente...         1          1   
1577  Add <iden> auto-configuration  <enter> Update ...         1          1   
1579  Fix NPE in  <file_name>  when migration.instal...         0          1   
1595  Update  <file_name> <enter> Replace line break...         1          1   

      predicted_decision  predicted_rationale  
9                      1                    1  
24                     1                    1  
31                     1                    1  
34                     1                    1  
36                     1                    1  
...                  ...                  ...  
1569                   1                    1  
1575                   1                    1  
1577                   1                    1  
1579                   1                    1  
1595                   1                    1  

[137 rows x 8 columns]

# ChatGPT decision/rationale  extraction

In [ ]:
!pip install openai

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.6/311.6 kB 4.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.6/75.6 kB 5.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 7.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 5.9 MB/s eta 0:00:00


In [ ]:
import os
from openai import OpenAI

secret_key = "sk-XXXX"

client = OpenAI(api_key=secret_key)

completion = client.chat.completions.create(
  model="gpt-3.5-turbo",
  messages=[
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": "Hello! 2+2?"}
  ]
)

print(completion.choices[0].message.content)



Hello! 2+2 equals 4. How can I assist you further today?


In [ ]:
def chatWithGPT(text):
  completion = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
      {"role": "system", "content": "You are a helpful assistant."},
      {"role": "user", "content": text}
    ]
  )
  print(completion.choices[0].message.content)
  return(completion.choices[0].message.content)

In [ ]:
import time
d = {'Decision': [], 'Rationale': []}

i = 0

for s in df_oss_commits_5_decision_rationale_sentences['new_message1'][90:]:
#for s in df_button_commits_decision_rationale_sentences['text'][150:200]:
  print(i, s)

  prompt = """
      Which chunks of this sentence indicate Decision and which chunks indicate Rationale?
      Decision is an action or a change that has been made, including a description of the patch behaviour.
      Rationale is the reason for a decision or value judgment.

      Your answer should be strictly in this format:
      Decision: XX
      Rationale: YY
      XX and YY must be chunks from the sentence in question.
      All sentences express both a Decision and the Rationale behind it.
      If you still can not find the decision or the rationale, only answer "None" instead of XX or YY.
      Do not add any other text in your answer.

      Example1:
      s = "Remove the mm_kill() function call because we do not use it anymore"
      Decision: Remove the mm_kill() function call
      Rationale: we do not use it anymore

      Example2:
      s = "Remove the unused mm_kill() function call"
      Decision: Remove the unused mm_kill() function call
      Rationale: unused

      Example3:
      s = "Fix this bug"
      Decision: Fix this bug
      Rationale: Fix

      Sentence :
      """

  answer = chatWithGPT(prompt + s)
  decision = answer.split('\nRationale: ')[0].split('Decision: ')[1]
  rationale = answer.split('\nRationale: ')[1]
  print((decision, 'has rationale', rationale))
  d['Decision'].append(decision)
  d['Rationale'].append(rationale)
  #time.sleep(20)
  i = i+1

df_graph = pd.DataFrame(data=d)
df_graph

0 Make fields private where possible 
Decision: Make fields private
Rationale: where possible
('Make fields private', 'has rationale', 'where possible')
1 Reduce logging in Travis 
Decision: Reduce logging in Travis
Rationale: N/A
('Reduce logging in Travis', 'has rationale', 'N/A')
2 Polish  <file_name> <enter> Aplly consistent formatting, drop JDK 8 support and cleanup repo locations to use spring.io. 
Decision: Apply consistent formatting, drop JDK 8 support, and cleanup repo locations to use spring.io.  
Rationale: Polish, consistent formatting, drop JDK 8 support, cleanup repo locations to use spring.io.  
('Apply consistent formatting, drop JDK 8 support, and cleanup repo locations to use spring.io.  ', 'has rationale', 'Polish, consistent formatting, drop JDK 8 support, cleanup repo locations to use spring.io.  ')
3 Make <iden> optional for <iden>  <enter> This commit removes the required dependency on `<iden>` instances when creating `<iden>` beans, making it optional. <enter> 

Decision  \
0                                 Make fields private   
1                            Reduce logging in Travis   
2   Apply consistent formatting, drop JDK 8 suppor...   
3                     Make <iden> optional for <iden>   
4                      Set <iden> in default <iden>     
5   Disallow all extensions in actuator endpoints ...   
6   Blitz some more special characters from the me...   
7   Add /error to ignored paths for security autoc...   
8             Fix broken test (use web app context)     
9                              Fix typo 'a' -> 'an'     
10                  Fix checkstyle header violation     
11                    Backport build script updates     
12  Make file detection more resilient across rest...   
13           Fix package name for boot-loader-tools     
14    Improve error handling in <iden> upgrade checks   
15                           Fix checkstyle violation   
16                  Add group property to <file_name>   
17     Fix <iden> deprecation <enter> See <pr_link>     
18     Fix link formatting in custom <iden> section     
19  Use JSONObject.putOpt in <file_name> <enter> C...   
20                      Remove duplicate word in docs   
21                                          Fix tests   
22  Remove unnecessary logging by start-docker scr...   
23  Fix profile precedence when active and include...   
24   Fix documentation for health endpoint security     
25      Send Slack Notifications when build completes   
26                      Rename samples to smoke tests   
27         Prepend without replacing in <file_name>     
28  Align expectations of various <iden> configura...   
29  Ensure JPA vendor properties are period separated   
30  Extract logic for duplicate file removal so it...   
31        Register an <iden> in security autoconfig     
32                         Fix freeMarker->freemarker   
33  Remove undefined <iden> appender from basic lo...   
34                            Add <iden> for <iden>     
35                              Fix typos in Javadocs   
36   Add hooks for failed application context startup   
37                             Add missing dependency   
38                                  Add README to cli   
39                                           Fix test   
40                     Add test for nested properties   
41       Align <file_name> Javadoc with documentation   
42    Add <file_name> option for <file_name> building   
43          Add XMLUnit to spring-boot-starter-test     
44  Update Spring <iden> auto-configuration so tha...   
45  Fix NPE in <file_name> when migration.installe...   
46  Update <file_name>, Replace line break with mi...   

                                            Rationale  
0                                      where possible  
1                                                 N/A  
2   Polish, consistent formatting, drop JDK 8 supp...  
3   This commit removes the required dependency on...  
4   Only affects the default <iden> (so when users...  
5   Along with the recent change in <iden> to use ...  
6   When MVC path matchers are used as metric keys...  
7   Protecting /error doesn't make a great deal of...  
8                                         broken test  
9                                            Fix typo  
10                                   See <issue_link>  
11                                               None  
12  Retain file snapshot state across devtools res...  
13                                   Issue: #53129653  
14                                      See <pr_link>  
15                                    see the PR link  
16                                      See <pr_link>  
17                                        deprecation  
18                                      See <pr_link>  
19                                               None  
20                                          duplicate  
21                                                Fix  
22                  

In [ ]:
df_graph.to_csv('ChatGPT_decision_rationale_oss_SPRINGBOOT_90_137.csv', sep=';', index=False)

Concat Files

In [ ]:
files= ['ChatGPT_decision_rationale_SLOB_0_50.csv' ,
        'ChatGPT_decision_rationale_SLOB_50_100.csv',
        'ChatGPT_decision_rationale_SLOB_100_150.csv',
        'ChatGPT_decision_rationale_SLOB_150_186.csv',
        'ChatGPT_decision_rationale_SLOB_187_200.csv',
         'ChatGPT_decision_rationale_SLOB_200_206.csv',
         'ChatGPT_decision_rationale_SLOB_207_220.csv',
         'ChatGPT_decision_rationale_SLOB_220_240.csv',
         'ChatGPT_decision_rationale_SLOB_240_252.csv'

   "ChatGPT_decision_rationale_BUTTON_0_50.csv",
         'ChatGPT_decision_rationale_BUTTON_50_100.csv',
         "ChatGPT_decision_rationale_BUTTON_100_150.csv",
         "ChatGPT_decision_rationale_BUTTON_150_191.csv"

         'ChatGPT_decision_rationale_oss_dubbo_0_50.csv',
         'ChatGPT_decision_rationale_oss_dubbo_50_100.csv',
         "ChatGPT_decision_rationale_oss_dubbo_100_150.csv",
         "ChatGPT_decision_rationale_oss_dubbo_150_171.csv"

    'ChatGPT_decision_rationale_oss_RETROFIT_0_50.csv',
     'ChatGPT_decision_rationale_oss_RETROFIT_50_80.csv',
     'ChatGPT_decision_rationale_oss_RETROFIT_80_90.csv',
     'ChatGPT_decision_rationale_oss_RETROFIT_90_100.csv',
     'ChatGPT_decision_rationale_oss_RETROFIT_100_138.csv',

        'ChatGPT_decision_rationale_oss_OKHTTP_0_50.csv',
        'ChatGPT_decision_rationale_oss_OKHTTP_50_100.csv',
         'ChatGPT_decision_rationale_oss_OKHTTP_100_140.csv',
         'ChatGPT_decision_rationale_oss_OKHTTP_140_151.csv'
]

In [ ]:
import os

files = [
        'ChatGPT_decision_rationale_oss_SPRINGBOOT_0_50.csv',
        'ChatGPT_decision_rationale_oss_SPRINGBOOT_50_70.csv',
        'ChatGPT_decision_rationale_oss_SPRINGBOOT_70_90.csv',
        'ChatGPT_decision_rationale_oss_SPRINGBOOT_90_137.csv'
         ]

li = []
path = '.'

for file in files:
    df = pd.read_csv(os.path.join(path, file), sep=';')
    li.append(df)
df = pd.concat(li, axis=0, ignore_index=True)

#df
df['new_message1'] = df_oss_commits_5_decision_rationale_sentences['new_message1'].values
df['url'] =  df_oss_commits_5_decision_rationale_sentences['url'].values
df = df[['url', 'new_message1', 'Decision', 'Rationale']]

df
df.to_csv('ChatGPT_decision_rationale_oss_SPRINGBOOT.csv', sep=';', index=False)

In [ ]:
for f in files:
  print(f)

ChatGPT_decision_rationale_oss_RETROFIT_0_50.csv
ChatGPT_decision_rationale_oss_RETROFIT_50_80.csv
ChatGPT_decision_rationale_oss_RETROFIT_80_90.csv
ChatGPT_decision_rationale_oss_RETROFIT_90_100.csv
ChatGPT_decision_rationale_oss_RETROFIT_100_138.csv


In [ ]:
df = pd.read_csv('ChatGPT_decision_rationale_oss_SPRINGBOOT.csv', sep=';')
df

url  \
0    https://github.com/spring-projects/spring-boot...   
1    https://github.com/spring-projects/spring-boot...   
2    https://github.com/spring-projects/spring-boot...   
3    https://github.com/spring-projects/spring-boot...   
4    https://github.com/spring-projects/spring-boot...   
..                                                 ...   
132  https://github.com/spring-projects/spring-boot...   
133  https://github.com/spring-projects/spring-boot...   
134  https://github.com/spring-projects/spring-boot...   
135  https://github.com/spring-projects/spring-boot...   
136  https://github.com/spring-projects/spring-boot...   

                                          new_message1  \
0    Fix typo `<iden>` -> `<iden>`  <enter> See  <p...   
1    Ensure checking customizer ordering  <enter> S...   
2    Fix conditions that lead to auto-configure <id...   
3    Fix documentation example  <enter> Previously,...   
4    Replace use of deprecated Reactor <iden> in te...   
..                                                 ...   
132  Add  <file_name>  option for  <file_name>  bui...   
133  Add XMLUnit to spring-boot-starter-test  <ente...   
134  Add <iden> auto-configuration  <enter> Update ...   
135  Fix NPE in  <file_name>  when migration.instal...   
136  Update  <file_name> <enter> Replace line break...   

                                              Decision  \
0                        Fix typo `<iden>` -> `<iden>`   
1                  Ensure checking customizer ordering   
2    Fix conditions that lead to auto-configure <id...   
3                   The nested class should be public.   
4    Replace use of deprecated Reactor <iden> in tests   
..                                                 ...   
132    Add <file_name> option for <file_name> building   
133          Add XMLUnit to spring-boot-starter-test     
134  Update Spring <iden> auto-configuration so tha...   
135  Fix NPE in <file_name> when migration.installe...   
136  Update <file_name>, Replace line break with mi...   

                                             Rationale  
0                                       See  <pr_link>  
1                                        See <pr_link>  
2                                        See <pr_link>  
3    The nested private static class would cause an...  
4                                   Fixes <issue_link>  
..                                                 ...  
132  This commit adds a <file_name> option to the c...  
133                                   Closes <pr_link>  
134  Prior to this commit `<iden>` interfaces would...  
135                                      See <pr_link>  
136                     to continue the property value  

[137 rows x 4 columns]

# Relationship extraction

## Remove None/NAN values

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('ChatGPT_decision_rationale_SLOB.csv', sep=';')
#df = pd.read_csv('ChatGPT_decision_rationale_BUTTON.csv', sep=';')
#df = pd.read_csv('ChatGPT_decision_rationale_oss_JUNIT.csv', sep=';')
#df = pd.read_csv('ChatGPT_decision_rationale_oss_dubbo.csv', sep=';')
#df = pd.read_csv('ChatGPT_decision_rationale_oss_RETROFIT.csv', sep=';')
#df = pd.read_csv('ChatGPT_decision_rationale_oss_OKHTTP.csv', sep=';')
#df = pd.read_csv('ChatGPT_decision_rationale_oss_SPRINGBOOT.csv', sep=';')

df


FileNotFoundError: [Errno 2] No such file or directory: 'ChatGPT_decision_rationale_SLOB.csv'

In [ ]:
df.fillna('None', inplace=True) # chnage NaN values with None from entire dataframe
df = df.drop(df[ (df.Decision == 'None') | (df.Decision == "none") | (df.Decision == "N/A")   ].index)
df = df.drop(df[ (df.Rationale == 'None') | (df.Rationale == "none") | (df.Rationale == "N/A")   ].index)
df = df.reset_index()
df

index                                           Decision  \
0        2     __alloc_size attribute was added to allocators   
1        3  For most allocations, this works well, as the ...   
2        4  it wants to minimize the number of calls to kr...   
3        5  Use all the space available in the chosen buck...   
4        6  kmalloc(size) might give us more room than req...   
..     ...                                                ...   
204    246  Introduce a memory-zeroing variant of kmem_cac...   
205    247                                                fix   
206    249          SLOB saving nearly half a megabyte of RAM   
207    250  Compare the sizes of vmlinux-slab and vmlinux-...   
208    251                   Fix 32-bitness bugs in mm/slob.c   

                                             Rationale  
0    In the effort to help the compiler reason abou...  
1    The vast majority of callers are not expecting...  
2                  so it can learn how large it is now  
3                 to avoid needing to reallocate later  
4               might give us more room than requested  
..                                                 ...  
204                             memory-zeroing variant  
205                                SLOB=y && SMP=y fix  
206          Comparison for otherwise identical builds  
207                      to analyze memory consumption  
208                                               bugs  

[209 rows x 3 columns]

In [ ]:
# df[ (df['Rationale']  == "None") | (df['Rationale'] == "none")  | (df['Rationale'] == "N/A") | (df['Decision'] == "None") | (df['Decision'] == "none") | (df['Decision'] == "N/A")   ]

In [ ]:
df[ (df['Rationale']  == "\nNone") | (df['Rationale'] == "none")  | (df['Rationale'] == "N/A") | (df['Decision'] == "None") | (df['Decision'] == "none") | (df['Decision'] == "N/A")   ]

index                                                url  \
102    150  https://github.com/apache/dubbo/commit/f490df8...   

                                          new_message1  \
102  keep demo simple, and switch to use zookeeper ...   

                                              Decision Rationale  
102  \nkeep demo simple, and switch to use zookeepe...    \nNone

In [ ]:
# save this dataframe somewhere
df.to_csv('ChatGPT_decision_rationale_triples_oss_SPRINGBOOT.csv', sep=';', index=False)

In [ ]:
# just to doublec echeck
df = pd.read_csv('ChatGPT_decision_rationale_triples_oss_dubbo.csv', sep=';')
#len(df)
df

index                                                url  \
0        2  https://github.com/apache/dubbo/commit/c21cc05...   
1        3  https://github.com/apache/dubbo/commit/317e62f...   
2        5  https://github.com/apache/dubbo/commit/71e04fb...   
3        7  https://github.com/apache/dubbo/commit/15d8084...   
4        8  https://github.com/apache/dubbo/commit/53dca53...   
..     ...                                                ...   
111    164  https://github.com/apache/dubbo/commit/16f7a1e...   
112    165  https://github.com/apache/dubbo/commit/9ca9bb0...   
113    166  https://github.com/apache/dubbo/commit/4dc0612...   
114    168  https://github.com/apache/dubbo/commit/bbacab0...   
115    169  https://github.com/apache/dubbo/commit/789775b...   

                                          new_message1  \
0    replace  <file_name>  log.isInfoEnabled->log.i...   
1    Fix concurrency problems in  <file_name>  and ...   
2    Fix <issue_link> Java <iden> use '_' split lan...   
3           Fix Dubbo-3990 <issue_link> ( <pr_link> )    
4             Remove redundant judgment ( <pr_link> )    
..                                                 ...   
111  Close all servers/ports after tests finish ( <...   
112                             Fix typo <issue_link>    
113  Update README.md ( <pr_link> )  <enter> add @o...   
114  Enhancement, support <iden> auto recognize in ...   
115  Change <iden> to regular list in  <file_name> ...   

                                              Decision  \
0    replace <file_name> log.isInfoEnabled->log.isW...   
1    Fix concurrency problems in <file_name> and <f...   
2    Fix <issue_link> Java <iden> use '_' split lan...   
3            Fix Dubbo-3990 <issue_link> ( <pr_link> )   
4              Remove redundant judgment ( <pr_link> )   
..                                                 ...   
111       Close all servers/ports after tests finish     
112                                           Fix typo   
113  Update README.md ( <pr_link> )  <enter> add @o...   
114  Support <iden> auto recognize in <file_name> (...   
115  Change <iden> to regular list in <file_name> (...   

                                     Rationale  
0                                            -  
1                         Concurrency problems  
2     use '_' split language, country, variant  
3                                          Fix  
4                                    redundant  
..                                         ...  
111                      Ensure proper cleanup  
112                                       typo  
113        to include the @override annotation  
114  Enhancement\n\nDecision: Fix <issue_link>  
115                            to regular list  

[116 rows x 5 columns]

In [ ]:
import itertools
all_combinaisons = list( itertools.combinations(df['Decision'], 2))
len(all_combinaisons)

21736

## Contradictions detection ~ run on the serveur

In [ ]:
import pandas as pd
# graph_dataframe = pd.read_csv('contradictions_11_batches_SLOB_0_5.csv', sep=';')
graph_dataframe = pd.read_csv('contradictions_4_batches_oss_dubbo_0_5.csv', sep=';')
graph_dataframe.loc[graph_dataframe['Alpha'] > 0.9]

Decision1  \
43            add <iden> for dynamically created class   
50   Fix <iden> and retries in <file_name> ( <pr_li...   
56   Fix <iden> and retries in <file_name> ( <pr_li...   
62   add switch of generic invocation with class in...   
90                         add comment for <file_name>   
96       add gpg signing plugin for protobuf compiler    
125  Introduce  <file_name>  to distinguish from <i...   
173   Add <file_name> name and fix <file_name> error     
197  Add package support for dubbo-remoting-netty4 ...   
215    add the router key in <file_name> (<pr_link>)\n   
288  Add a remoting redis to adapt mono, sentinel a...   
307                Add `how can I contribute?` section   

                                            Rationale1  \
43                                 dynamically created   
50                                     Fix and retries   
56                                     Fix and retries   
62                                                 fix   
90                                    see <issue_link>   
96                               for protobuf compiler   
125                            distinguish from <iden>   
173                                              error   
197                                    package support   
215                                                  -   
288  to adapt mono, sentinel and cluster redis; ref...   
307                                                  -   

                                             Decision2  \
43             rename package name from <iden> to impl   
50         Ignore unit test <file_name> (no zk server)   
56                                    Refactor: remove   
62                                    Refactor: remove   
90   \nkeep demo simple, and switch to use zookeepe...   
96                                    Refactor: remove   
125        Ignore unit test <file_name> (no zk server)   
173                                   Refactor: remove   
197                                   Refactor: remove   
215                                   Refactor: remove   
288                                   Refactor: remove   
307                                   Refactor: remove   

                                          Rationale2 Relationship     Alpha  
43                                                 -  Contradicts  0.964985  
50                                      no zk server  Contradicts  0.961431  
56   and replace it with <method_name> ( <pr_link> )  Contradicts  0.914636  
62   and replace it with <method_name> ( <pr_link> )  Contradicts  0.916576  
90                                            \nNone  Contradicts  0.996236  
96   and replace it with <method_name> ( <pr_link> )  Contradicts  0.962524  
125                                     no zk server  Contradicts  0.936521  
173  and replace it with <method_name> ( <pr_link> )  Contradicts  0.983772  
197  and replace it with <method_name> ( <pr_link> )  Contradicts  0.944061  
215  and replace it with <method_name> ( <pr_link> )  Contradicts  0.981239  
288  and replace it with <method_name> ( <pr_link> )  Contradicts  0.990472  
307  and replace it with <method_name> ( <pr_link> )  Contradicts  0.981047

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.


## Similarities detection ~ run on server

results

In [ ]:
import pandas as pd

# graph_dataframe = pd.read_csv('similarities_SLOB_0_5.csv', sep=';')
# graph_dataframe = pd.read_csv('similarities_BUTTON_0_5.csv', sep=';')
graph_dataframe = pd.read_csv('similarities_oss_JUNIT_0_5.csv', sep=';')


graph_dataframe.loc[graph_dataframe['Alpha'] > 0.5]

Decision1  \
0                       Fix <method_name> ( <pr_link> )   
1                       Fix <method_name> ( <pr_link> )   
2                       Fix <method_name> ( <pr_link> )   
3                       Fix <method_name> ( <pr_link> )   
4                       Fix <method_name> ( <pr_link> )   
...                                                 ...   
3151          surefire and javadoc maven plugin updates   
3152          surefire and javadoc maven plugin updates   
3153  Reused <iden> instead of own defined class <en...   
3154  Reused <iden> instead of own defined class <en...   
3155   Removed the unnecessary <iden>: block in javadoc   

                                             Rationale1  \
0     <method_name> should not match when the given ...   
1     <method_name> should not match when the given ...   
2     <method_name> should not match when the given ...   
3     <method_name> should not match when the given ...   
4     <method_name> should not match when the given ...   
...                                                 ...   
3151                                            updates   
3152                                            updates   
3153              more inline with the rest of the file   
3154              more inline with the rest of the file   
3155                                        unnecessary   

                                              Decision2  \
0     Wrap the invocation of <iden>() within a try-c...   
1     Fix dead link to the ant task in <file_name> (...   
2      Fix many warnings (Eclipse <version>/Juno based)   
3     changed the <iden>() method to accept a <iden>...   
4                        Remove redundant field <iden>    
...                                                 ...   
3151   Removed the unnecessary <iden>: block in javadoc   
3152  remove f prefix from field names, add <file_na...   
3153   Removed the unnecessary <iden>: block in javadoc   
3154  remove f prefix from field names, add <file_na...   
3155  remove f prefix from field names, add <file_na...   

                                             Rationale2 Relationship     Alpha  
0     Exceptions from <iden>() were causing unrooted...      Similar  0.677116  
1     The link is dead; task has been moved to anoth...      Similar  0.593965  
2     Enh: add new staticondemandthreshold setting t...      Similar  0.575055  
3                       made some documentation changes      Similar  0.712074  
4                                             redundant      Similar  0.669187  
...                                                 ...          ...       ...  
3151                                        unnecessary      Similar  0.620277  
3152         reformatting and standardizing field names      Similar  0.513130  
3153                                        unnecessary      Similar  0.663909  
3154         reformatting and standardizing field names      Similar  0.604362  
3155         reformatting and standardizing field names      Similar  0.746631  

[3156 rows x 6 columns]

# Conflicts detection

In [ ]:
import pandas as pd

In [ ]:
!pip install sentence_transformers

In [ ]:
from sentence_transformers import SentenceTransformer, util

def check_similarity(sentence1, sentence2):
  #model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')
  model = SentenceTransformer('distilbert-base-nli-mean-tokens')

  #Compute embedding for both lists
  embedding_1= model.encode(sentence1, convert_to_tensor=True)
  embedding_2 = model.encode(sentence2, convert_to_tensor=True)

  res = util.pytorch_cos_sim(embedding_1, embedding_2)
  print(res)
  return float(res[0][0])


In [ ]:
# Code to test 1 pair only, not batches
from transformers import pipeline


def detect_contradiction_nli_one_pair(sentence1, sentence2):
    pipe = pipeline( model="roberta-large-mnli", device='cuda:0')

    # Concatenate the sentences and get predictions
    sentence_pairs = str(sentence1 + sentence2)
    predictions = pipe(sentence_pairs)
    print(predictions)

    # Extract prediction +  score
    label = predictions[0]['label']
    score = predictions[0]['score']

    if label == 'CONTRADICTION' and score > 0.5:
      return True, score
    else:
      return False, 0.0

## Consistency Mechanism 1

In [ ]:
# Does similar decisions have contradictory rationales  ?
from tqdm import tqdm

def consistency_mechanisms_1(graph_dataframe):

  nb_similar = len(graph_dataframe[graph_dataframe['Relationship'] == 'Similar'])

  inconsistencies_dataframe = graph_dataframe.copy()
  inconsistencies_dataframe['similarity_rationales'] = None
  inconsistencies_dataframe['contradiction_rationales'] = None

  for ind in tqdm(graph_dataframe.index):
      if graph_dataframe['Relationship'][ind] == 'Similar':
        s = check_similarity(graph_dataframe['Rationale1'][ind], graph_dataframe['Rationale2'][ind])
        # pred, c = check_entailement(graph_dataframe['Rationale1'][ind], graph_dataframe['Rationale2'][ind])
        contradiction_detected, contradiction_strength = detect_contradiction_nli_one_pair(graph_dataframe['Rationale1'][ind], graph_dataframe['Rationale2'][ind])

        inconsistencies_dataframe['similarity_rationales'][ind] = s
        if contradiction_detected:
          inconsistencies_dataframe['contradiction_rationales'][ind] =  contradiction_strength

  inconsistencies_dataframe.to_csv('similarities_inconsistencies_mechanism1_SPRINGBOOT.csv', sep=';', index=False)

In [ ]:
import pandas as pd
# graph_dataframe = pd.read_csv('similarities_BUTTON_0_5.csv', sep=';')
graph_dataframe = pd.read_csv('similarities_oss_dubbo_0_5.csv', sep=';')

#graph_dataframe = pd.read_csv('similarities_oss_RETROFIT_0_5.csv', sep=';')
#graph_dataframe = pd.read_csv('similarities_oss_OKHTTP_0_5.csv', sep=';')
#graph_dataframe = pd.read_csv('similarities_oss_SPRINGBOOT_0_5.csv', sep=';')

graph_dataframe = graph_dataframe.loc[graph_dataframe['Alpha'] > 0.8]  # keep tyhis higher alpha 0.8 for all validation
graph_dataframe

Decision1  \
0     replace <file_name> log.isInfoEnabled->log.isW...   
7     replace <file_name> log.isInfoEnabled->log.isW...   
12    replace <file_name> log.isInfoEnabled->log.isW...   
30    replace <file_name> log.isInfoEnabled->log.isW...   
36    replace <file_name> log.isInfoEnabled->log.isW...   
...                                                 ...   
4730                                   Refactor: remove   
4758                 Remove unused import for unit test   
4802                 switch from <iden> to regular list   
4836  Update README.md ( <pr_link> )  <enter> add @o...   
4837  Support <iden> auto recognize in <file_name> (...   

                                             Rationale1  \
0                                                     -   
7                                                     -   
12                                                    -   
30                                                    -   
36                                                    -   
...                                                 ...   
4730    and replace it with <method_name> ( <pr_link> )   
4758                                clear unused import   
4802  in order to avoid potential UnsupportedOperati...   
4836                to include the @override annotation   
4837          Enhancement\n\nDecision: Fix <issue_link>   

                                              Decision2  \
0     Fix concurrency problems in <file_name> and <f...   
7     Fix <iden> and retries in <file_name> ( <pr_li...   
12    fix alibaba <file_name> setAttachment(<iden>) ...   
30                             Fix NPE in <file_name>     
36     Add <file_name> name and fix <file_name> error     
...                                                 ...   
4730                     remove the space ( <pr_link> )   
4758                     remove the space ( <pr_link> )   
4802  Change <iden> to regular list in <file_name> (...   
4836  Change <iden> to regular list in <file_name> (...   
4837  Change <iden> to regular list in <file_name> (...   

                 Rationale2 Relationship     Alpha  
0      Concurrency problems      Similar  0.808314  
7           Fix and retries      Similar  0.866127  
12                   bugfix      Similar  0.850784  
30                      Fix      Similar  0.818685  
36                    error      Similar  0.838880  
...                     ...          ...       ...  
4730  follow up for pr#4339      Similar  0.886657  
4758  follow up for pr#4339      Similar  0.824283  
4802        to regular list      Similar  0.834587  
4836        to regular list      Similar  0.800808  
4837        to regular list      Similar  0.848346  

[365 rows x 6 columns]

In [ ]:
consistency_mechanisms_1(graph_dataframe) # nli_detect_one_pair >0.5

In [ ]:
#similarities_inconsistencies_dataframe = pd.read_csv('similarities_inconsistencies_mechanism1_SLOB.csv', sep=';')
#similarities_inconsistencies_dataframe = pd.read_csv('similarities_inconsistencies_mechanism1_BUTTON.csv', sep=';')

#similarities_inconsistencies_dataframe = pd.read_csv('similarities_inconsistencies_mechanism1_oss_JUNIT.csv', sep=';')
similarities_inconsistencies_dataframe = pd.read_csv('similarities_inconsistencies_mechanism1_DUBBO.csv', sep=';')
#similarities_inconsistencies_dataframe = pd.read_csv('similarities_inconsistencies_mechanism1_RETROFIT.csv', sep=';')
#similarities_inconsistencies_dataframe = pd.read_csv('similarities_inconsistencies_mechanism1_OKHTTP.csv', sep=';')
#similarities_inconsistencies_dataframe = pd.read_csv('similarities_inconsistencies_mechanism1_SPRINGBOOT.csv', sep=';')


similarities_inconsistencies_dataframe[ similarities_inconsistencies_dataframe['contradiction_rationales'] > 0.6]

Decision1  \
71   reduce the level of request data in timeout lo...   
77   Reduce memory allocation during address change...   
200                        Remove duplicate ut classes   
308                      fix typo:<iden> ( <pr_link> )   
356         Reduce object allocation for <method_name>   
364  Support <iden> auto recognize in <file_name> (...   

                                            Rationale1  \
71                          to control the size of log   
77   reduce allocation during export and refer at s...   
200                                          duplicate   
308                                               typo   
356                                            -\nNone   
364          Enhancement\n\nDecision: Fix <issue_link>   

                                             Decision2  \
71          Reduce object allocation for <method_name>   
77          Reduce object allocation for <method_name>   
200         Reduce object allocation for <method_name>   
308  Support <iden> auto recognize in <file_name> (...   
356                                   Refactor: remove   
364  Change <iden> to regular list in <file_name> (...   

                                          Rationale2 Relationship     Alpha  \
71                                           -\nNone      Similar  0.873967   
77                                           -\nNone      Similar  0.834707   
200                                          -\nNone      Similar  0.862736   
308        Enhancement\n\nDecision: Fix <issue_link>      Similar  0.810978   
356  and replace it with <method_name> ( <pr_link> )      Similar  0.807586   
364                                  to regular list      Similar  0.848346   

     similarity_rationales  contradiction_rationales  
71                0.429001                  0.691089  
77                0.497535                  0.848583  
200               0.766187                  0.738912  
308               0.523329                  0.627469  
356               0.471574                  0.644738  
364               0.451027                  0.903474

In [ ]:
len(similarities_inconsistencies_dataframe[ similarities_inconsistencies_dataframe['contradiction_rationales'] > 0.6])

14

## Consistency Mechanism 2

In [ ]:
import pandas as pd
#graph_dataframe = pd.read_csv('contradictions_3_batches_oss_JUNIT_0_5.csv', sep=';')
#graph_dataframe = pd.read_csv('contradictions_7_batches_BUTTON_0_5.csv', sep=';')
# graph_dataframe = pd.read_csv('contradictions_11_batches_SLOB_0_5.csv', sep=';')

graph_dataframe = pd.read_csv('contradictions_4_batches_oss_dubbo_0_5.csv', sep=';')
#graph_dataframe = pd.read_csv('contradictions_3_batches_oss_RETROFIT_0_5.csv', sep=';')
#graph_dataframe = pd.read_csv('contradictions_4_batches_oss_OKHTTP_0_5.csv', sep=';')
#graph_dataframe = pd.read_csv('contradictions_4_batches_oss_SPRINGBOOT_0_5.csv', sep=';')

graph_dataframe = graph_dataframe.loc[graph_dataframe['Alpha'] > 0.8] # consider the contradicts dataframe , keep this value for all validation
graph_dataframe

Decision1  \
15   Fix <issue_link> Java <iden> use _ split langu...   
22   Fix <issue_link> Java <iden> use _ split langu...   
41            add <iden> for dynamically created class   
43            add <iden> for dynamically created class   
50   Fix <iden> and retries in <file_name> ( <pr_li...   
56   Fix <iden> and retries in <file_name> ( <pr_li...   
62   add switch of generic invocation with class in...   
63   add switch of generic invocation with class in...   
90                         add comment for <file_name>   
92                add start status for <iden> server     
94                add start status for <iden> server     
96       add gpg signing plugin for protobuf compiler    
97       add gpg signing plugin for protobuf compiler    
103  implements future and keep  <file_name>  backw...   
106  implements future and keep  <file_name>  backw...   
113                        Save <file_name> allocation   
116                        Save <file_name> allocation   
125  Introduce  <file_name>  to distinguish from <i...   
173   Add <file_name> name and fix <file_name> error     
174   Add <file_name> name and fix <file_name> error     
197  Add package support for dubbo-remoting-netty4 ...   
210           add maven-compiler-plugin to <file_name>   
212    add the router key in <file_name> (<pr_link>)\n   
214    add the router key in <file_name> (<pr_link>)\n   
215    add the router key in <file_name> (<pr_link>)\n   
216    add the router key in <file_name> (<pr_link>)\n   
288  Add a remoting redis to adapt mono, sentinel a...   
296  Revert fix wrong check of <iden> when export a...   
301          Adding the new methods into <file_name>     
304  Adding the overriding rule for <file_name> (<p...   
305                Add `how can I contribute?` section   
307                Add `how can I contribute?` section   
308                Add `how can I contribute?` section   
318                      Modify comments and imports     
341                             add jdk11 to travis ci   

                                            Rationale1  \
15              use _ split language, country, variant   
22              use _ split language, country, variant   
41                                 dynamically created   
43                                 dynamically created   
50                                     Fix and retries   
56                                     Fix and retries   
62                                                 fix   
63                                                 fix   
90                                    see <issue_link>   
92                                                   -   
94                                                   -   
96                               for protobuf compiler   
97                               for protobuf compiler   
103                 future and backward compatibility.   
106                 future and backward compatibility.   
113                                 Performance tuning   
116                                 Performance tuning   
125                            distinguish from <iden>   
173                                              error   
174                                              error   
197                                    package support   
210                       to use Maven compiler plugin   
212                                                  -   
214                                                  -   
215                                                  -   
216                                                  -   
288  to adapt mono, sentinel and cluster redis; ref...   
296                                    fix wrong check   
301  to manipulate the exported <iden> for service ...   
304                                        Enhancement   
305                                                  -   
307                                                  -   
308                                       

In [ ]:
# Does contradictory decisions have similar rationales  ?
from tqdm import tqdm

inconsistencies_dataframe = graph_dataframe.copy()

def consistency_mechanisms_2(graph_dataframe):

  inconsistencies_dataframe['similarity_rationales'] = None
  #inconsistencies_dataframe['contradiction_rationales'] = None

  for ind in tqdm(graph_dataframe.index):
      if graph_dataframe['Relationship'][ind] == 'Contradicts':
        s = check_similarity(graph_dataframe['Rationale1'][ind], graph_dataframe['Rationale2'][ind])
        #contradiction_detected, contradiction_strength = detect_contradiction_nli(graph_dataframe['Rationale1'][ind], graph_dataframe['Rationale2'][ind])

        inconsistencies_dataframe['similarity_rationales'][ind] = s

  inconsistencies_dataframe.to_csv('contradictions_inconsistencies_mechanism2_DUBBO.csv', sep=';', index=False)

In [ ]:
consistency_mechanisms_2( graph_dataframe )

  0%|          | 0/35 [00:00<?, ?it/s]<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
  3%|▎         | 1/35 [00:01<00:35,  1.03s/it]

tensor([[0.5974]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
  6%|▌         | 2/35 [00:01<00:31,  1.05it/s]

tensor([[0.6970]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
  9%|▊         | 3/35 [00:02<00:27,  1.18it/s]

tensor([[0.5398]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
 11%|█▏        | 4/35 [00:03<00:24,  1.26it/s]

tensor([[0.7704]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
 14%|█▍        | 5/35 [00:04<00:22,  1.31it/s]

tensor([[0.2489]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
 17%|█▋        | 6/35 [00:04<00:23,  1.26it/s]

tensor([[0.6813]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
 20%|██        | 7/35 [00:05<00:21,  1.30it/s]

tensor([[0.6548]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
 23%|██▎       | 8/35 [00:06<00:21,  1.24it/s]

tensor([[0.6677]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
 26%|██▌       | 9/35 [00:07<00:20,  1.26it/s]

tensor([[0.5270]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
 29%|██▊       | 10/35 [00:08<00:19,  1.26it/s]

tensor([[0.5990]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
 31%|███▏      | 11/35 [00:08<00:18,  1.30it/s]

tensor([[0.4729]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
 34%|███▍      | 12/35 [00:09<00:18,  1.26it/s]

tensor([[0.6004]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
 37%|███▋      | 13/35 [00:10<00:17,  1.27it/s]

tensor([[0.3107]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
 40%|████      | 14/35 [00:11<00:16,  1.26it/s]

tensor([[0.2708]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
 43%|████▎     | 15/35 [00:12<00:17,  1.17it/s]

tensor([[0.5638]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
 46%|████▌     | 16/35 [00:13<00:16,  1.17it/s]

tensor([[0.2825]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
 49%|████▊     | 17/35 [00:13<00:15,  1.16it/s]

tensor([[0.6917]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
 51%|█████▏    | 18/35 [00:14<00:14,  1.20it/s]

tensor([[0.4622]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
 54%|█████▍    | 19/35 [00:15<00:12,  1.23it/s]

tensor([[0.5915]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
 57%|█████▋    | 20/35 [00:16<00:11,  1.29it/s]

tensor([[0.6780]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
 60%|██████    | 21/35 [00:16<00:10,  1.30it/s]

tensor([[0.6050]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
 63%|██████▎   | 22/35 [00:17<00:09,  1.31it/s]

tensor([[0.6460]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
 66%|██████▌   | 23/35 [00:18<00:09,  1.29it/s]

tensor([[0.5378]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
 69%|██████▊   | 24/35 [00:19<00:08,  1.25it/s]

tensor([[0.6560]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
 71%|███████▏  | 25/35 [00:20<00:08,  1.22it/s]

tensor([[0.5990]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
 74%|███████▍  | 26/35 [00:20<00:07,  1.26it/s]

tensor([[0.4159]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
 77%|███████▋  | 27/35 [00:22<00:09,  1.13s/it]

tensor([[0.5525]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
 80%|████████  | 28/35 [00:29<00:19,  2.73s/it]

tensor([[0.5978]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
 83%|████████▎ | 29/35 [00:31<00:15,  2.55s/it]

tensor([[0.7385]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
 86%|████████▌ | 30/35 [00:32<00:10,  2.19s/it]

tensor([[0.5441]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
 89%|████████▊ | 31/35 [00:33<00:07,  1.84s/it]

tensor([[0.6560]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
 91%|█████████▏| 32/35 [00:34<00:04,  1.61s/it]

tensor([[0.5990]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
 94%|█████████▍| 33/35 [00:35<00:02,  1.40s/it]

tensor([[0.7849]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
 97%|█████████▋| 34/35 [00:36<00:01,  1.26s/it]

tensor([[0.6410]])


<ipython-input-23-df775c69c7bf>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inconsistencies_dataframe['similarity_rationales'][ind] = s
100%|██████████| 35/35 [00:37<00:00,  1.07s/it]

tensor([[0.1456]])


In [ ]:
#contradictions_inconsistencies_dataframe = pd.read_csv('contradictions_inconsistencies_mechanism2_SLOB.csv', sep=';')
contradictions_inconsistencies_dataframe = pd.read_csv('contradictions_inconsistencies_mechanism2_BUTTON.csv', sep=';')

#contradictions_inconsistencies_dataframe = pd.read_csv('contradictions_inconsistencies_mechanism2_oss_JUNIT.csv', sep=';')
#contradictions_inconsistencies_dataframe = pd.read_csv('contradictions_inconsistencies_mechanism2_DUBBO.csv', sep=';')

contradictions_inconsistencies_dataframe = pd.read_csv('contradictions_inconsistencies_mechanism2_RETROFIT.csv', sep=';')
#contradictions_inconsistencies_dataframe = pd.read_csv('contradictions_inconsistencies_mechanism2_OKHTTP.csv', sep=';')
#contradictions_inconsistencies_dataframe = pd.read_csv('contradictions_inconsistencies_mechanism2_SPRINGBOOT.csv', sep=';')


contradictions_inconsistencies_dataframe[ contradictions_inconsistencies_dataframe['similarity_rationales'] > 0.6 ]

Decision1  \
0   Added a <file_name> rule for the line indentat...   
1   Added a <file_name> rule for the line indentat...   
12  Rename <method_name> to onSuccess(), and failu...   
15  Refactor <iden> tests to avoid the use of bloc...   
18  Propagate callback executor even when not expl...   
20  Use new <iden>s non-throwing close and a simpl...   
23  Switch to a generic to/from  <file_name> , exp...   
24  Update RxJava to the specified version with an...   
27                     Fix IntelliJ auto-formatting     
28       Add converters module and protobuf converter   
33                  Remove unused <file_name> classes   

                                           Rationale1  \
0                                         Indentation   
1                                         Indentation   
12              to onSuccess(), and failure(), <iden>   
15                avoid the use of blocking operators   
18  This lets custom <iden> implementations use th...   
20  non-throwing close and a simpler body\t\t\t         
23  This allows for specialization based on for wh...   
24  In case someone is relying on the transitive d...   
27                             Improve the formatting   
28                                    to the sentence   
33                                             unused   

                                            Decision2  \
0   Revert Revert Allow  <file_name>  instantiatio...   
1     Reintroduced deprecated <file_name> constructor   
12    Reintroduced deprecated <file_name> constructor   
15    Reintroduced deprecated <file_name> constructor   
18  Switch to a generic to/from  <file_name> , exp...   
20    Reintroduced deprecated <file_name> constructor   
23                    rename <iden> ->  <file_name>     
24    Reintroduced deprecated <file_name> constructor   
27  Revert Revert Allow  <file_name>  instantiatio...   
28  Revert Revert Allow  <file_name>  instantiatio...   
33    Reintroduced deprecated <file_name> constructor   

                                           Rationale2 Relationship     Alpha  \
0             This reverts commit  <otherCommit_link>  Contradicts  0.833260   
1                                          deprecated  Contradicts  0.895595   
12                                         deprecated  Contradicts  0.805563   
15                                         deprecated  Contradicts  0.814289   
18  This allows for specialization based on for wh...  Contradicts  0.890898   
20                                         deprecated  Contradicts  0.980917   
23           to harvest the names for new annotations  Contradicts  0.851387   
24                                         deprecated  Contradicts  0.831566   
27            This reverts commit  <otherCommit_link>  Contradicts  0.808670   
28            This reverts commit  <otherCommit_link>  Contradicts  0.861632   
33                                         deprecated  Contradicts  0.968499   

    similarity_rationales  
0                0.675248  
1                0.718161  
12               0.803653  
15               0.693817  
18               0.776564  
20               0.608568  
23               0.709038  
24               0.605633  
27               0.702041  
28               0.725306  
33               0.827122

In [ ]:
len(contradictions_inconsistencies_dataframe[ contradictions_inconsistencies_dataframe['similarity_rationales'] > 0.6 ])

8